version: '3.4'

services:
  webuserinterface:
    image: ${DOCKER_REGISTRY-}webuserinterface
    build:
      context: .
      dockerfile: WebUserInterface/Dockerfile

  weatherforecastapi:
    image: ${DOCKER_REGISTRY-}weatherforecastapi
    build:
      context: .
      dockerfile: WeatherForecastAPI/Dockerfile

  dbSqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

networks:
  docker-network:
    external: true