version: '3.4'

services:
  webuserinterface:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - WEATHERFORECASTAPI_URL=weatherforecastapi:80
    ports:
      - "0.0.0.0:4000:80"
      - "0.0.0.0:4001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - docker-network

  weatherforecastapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=DbSqlServer;Database=WeatherForecastDb;User Id=sa;Password=1Secure*Password1
    depends_on:
      - dbSqlServer
    ports:
      - "0.0.0.0:5001:80"
    networks:
      - docker-network

  dbSqlServer:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "0.0.0.0:6001:1433"
    networks:
      - docker-network
