version: '3.4'

services:
  dbSqlServer:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "6001:1433"

  weatherforecastapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=dbSqlServer;Database=WeatherForecastDb;User Id=sa;Password=1Secure*Password1
    ports:
      - "5001:80"
