version: '3.4'

services:
  dbSqlServer:
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  weatherforecastapi:
    image: ${DOCKER_REGISTRY-}weatherforecastapi
    build:
      context: .
      dockerfile: WeatherForecastAPI/Dockerfile
    depends_on:
      - dbSqlServer